// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kceggzvolonyqavvowwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjZWdnenZvbG9ueXFhdnZvd3djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDkwODksImV4cCI6MjA3MTk4NTA4OX0.R1emyOYS-bQLkP2RrmfXSKaBSwwxmZKmb6pAbyla5As";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});